version: "3"
services:
  hubot:
    image: 3ch01c/hubot
    container_name: hubot
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_URL=redis://redis:6379/hubot
      - HUBOT_SLACK_TOKEN=xoxb-YOUR-TOKEN-HERE
    links:
      - redis
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
      - ./data:/data
